"""
Store Vision AI
Machine Learning Feature Adapter

Converts Store Vision AI event data into the feature format
expected by the ML theft-risk model.
"""

from dataclasses import dataclass


@dataclass
class CustomerSession:
    """Structured information about one customer session."""

    dwell_time: float = 0.0
    item_interactions: int = 0
    items_picked: int = 0
    items_returned: int = 0
    movement_speed: float = 0.0
    shelf_visits: int = 0
    exit_without_billing: int = 0
    billing_mismatch: int = 0


def create_ml_features(session: CustomerSession) -> dict:
    """
    Convert a customer session into the feature dictionary
    expected by the ML model.
    """

    return {
        "dwell_time": float(session.dwell_time),
        "item_interactions": int(session.item_interactions),
        "items_picked": int(session.items_picked),
        "items_returned": int(session.items_returned),
        "movement_speed": float(session.movement_speed),
        "shelf_visits": int(session.shelf_visits),
        "exit_without_billing": int(session.exit_without_billing),
        "billing_mismatch": int(session.billing_mismatch),
    }


if __name__ == "__main__":

    # Example event generated by the future
    # Store Vision AI tracking layer.

    session = CustomerSession(
        dwell_time=75,
        item_interactions=5,
        items_picked=3,
        items_returned=1,
        movement_speed=1.4,
        shelf_visits=6,
        exit_without_billing=0,
        billing_mismatch=0,
    )

    features = create_ml_features(session)

    print("===================================")
    print("STORE VISION AI")
    print("ML FEATURE ADAPTER")
    print("===================================")

    for name, value in features.items():
        print(f"{name}: {value}")